### PR TITLE
Adding a new package for strain design

### PR DESCRIPTION
**Pull request by VonAlphaBisZulu**
Hi,

Our group (Steffen Klamt's lab at Max Planck Institute Magdeburg) has developed a new COBRApy-based package for MILP-based computational strain design. We'd be happy if it was added to the packages-website. The paper is currently revised and the documentation will be completed in the coming days. I'll keep you posted and activate the pull request once we're ready.

Best,
Philipp

### CODE REVIEW

**Comment by Midnighter** [comment]
Cool,we'd be happy to add it to the website. I see that in the description you say that you support SCIP. Since optlang doesn't support it yet, does that mean, StrainDesign has its own solver interfaces?

**Comment by VonAlphaBisZulu** [comment]
Yes, that is correct. We use the same interfaces that optlang uses (e.g. swiglpk, official CPLEX and Gurobi), but we don't use optlang. For SCIP, the reason is simply that it is not supported yet. For CPLEX and Gurobi the reson is that indicator constraints, which make most MILP computations more stable, are not (yet?) supported. For GLPK we could have used optlang, but since we unified some function names, we would have had to use a wrapper anyway, so a bottom-up solution was cleaner and not be affected by any changes introduced to optlang in the future.

**Comment by cdiener** [comment]
Looks like we should add indicator constraints to the optlang CPLEX and Gurobi interfaces then. Either way it still uses cobrapy so we would be more than happy to add it to the website. So let us know when you think the PR is done and we will merge.

**Comment by VonAlphaBisZulu** [comment]
Could you please accept the pull request to add the package to the website?

**Review by Midnighter — APPROVED** [review]
Looks good to me.

**Pull request merged**
