### PR TITLE
feat: add packages

### PR DESCRIPTION
**Pull request by hredestig**
cobrame, macking and optlang. Also fix url for cameo. 

Any additions, changes, @mmundy42? @KristianJensen? @coltonlloyd?

### CODE REVIEW

**Comment by mmundy42** [comment]
Looks good (and I'll have a MMinte package coming soon).

**Comment by cdiener** [comment]
LGTM. Will probably bundle this with a small fix for a dead link and some more packages before making the PR in the cobrapy repo. 

@mmundy42 I already added MMinte some time ago, if the package is done we can change the links in the markdown file.

**Comment by coltonlloyd** [comment]
Everything looks good to me. Thanks!

**Comment by KristianJensen** [comment]
Looks good to me as well 👍

**Pull request merged**
